### PR TITLE
Update numerizer to 2.0

### PR DESCRIPTION
**Pull request by davispuh**
Update numerizer to 2.0. All tests does pass.

### CODE REVIEW

**Comment by asurin** [comment]
:+1: for this!

**Comment by andrew** [comment]
Would be great to get this merged 👍

**Comment by Juanmcuello** [comment]
@henrypoydar , any chance you can take a look at this? Thanks!

**Comment by Juanmcuello** [comment]
Thanks @henrypoydar for the quick response. Do you plan to make a new release soon?

**Pull request merged**
